# Generated by Django 3.0.5 on 2020-06-17 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_tlp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3012)]),
        ),
    ]
