# Generated by Django 3.0.5 on 2020-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_tags_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='media',
            field=models.FileField(upload_to='File/'),
        ),
    ]
