# Generated by Django 3.0.5 on 2020-06-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='slugs',
        ),
    ]
