# Generated by Django 3.0.5 on 2020-06-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200618_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slugs',
            new_name='slug',
        ),
    ]
