# Generated by Django 3.0.5 on 2020-06-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200618_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_sampul',
            field=models.ImageField(blank=True, null=True, upload_to='sampul/'),
        ),
    ]
