# Generated by Django 3.0.5 on 2020-06-23 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_image_sampul'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='likes',
            field=models.ManyToManyField(related_name='artikel_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
