# Generated by Django 3.0.5 on 2020-06-24 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_artikel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
