# Generated by Django 3.0.5 on 2020-06-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='date_created',
        ),
    ]
